-- Create the personality schema if it doesn't exist
create schema if not exists personality;

-- Grant usage permissions to the relevant roles
grant usage on schema personality to anon, authenticated, service_role;
grant usage on schema personality to postgres;

-- Ensure roles can select from tables in this schema
grant all on all tables in schema personality to anon, authenticated, service_role;
grant all on all sequences in schema personality to anon, authenticated, service_role;
grant all on all routines in schema personality to anon, authenticated, service_role;

alter default privileges in schema personality grant all on tables to anon, authenticated, service_role;
alter default privileges in schema personality grant all on sequences to anon, authenticated, service_role;
alter default privileges in schema personality grant all on routines to anon, authenticated, service_role;


-- 1. Create a `profiles` table to store extra user data (like roles) beyond what Supabase Auth stores
create table personality.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text not null,
  role text default 'USER'::text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on profiles
alter table personality.profiles enable row level security;

-- Create policies for profiles
create policy "Personality profiles are viewable by everyone." on personality.profiles
  for select using (true);

create policy "Users can insert their own profile." on personality.profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on personality.profiles
  for update using (auth.uid() = id);

-- Trigger to automatically create a profile entry when a new auth user signs up
create or replace function personality.handle_new_user()
returns trigger as $$
begin
  insert into personality.profiles (id, email, role)
  values (new.id, new.email, 'USER');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure personality.handle_new_user();


-- 2. Create the `questions` table
create table personality.questions (
  id bigint generated by default as identity primary key,
  text text not null,
  type_associated integer not null check (type_associated >= 1 and type_associated <= 9),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS and make questions readable by everyone
alter table personality.questions enable row level security;
create policy "Questions are viewable by everyone." on personality.questions for select using (true);


-- 3. Create the `submissions` table
create table personality.submissions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references personality.profiles(id) on delete cascade not null,
  raw_answers jsonb not null,
  calculated_type integer not null check (calculated_type >= 1 and calculated_type <= 9),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on submissions
alter table personality.submissions enable row level security;
-- Users can insert their own submissions
create policy "Users can insert their own submissions." on personality.submissions for insert with check (auth.uid() = user_id);
-- Users can view their own submissions
create policy "Users can view their own submissions." on personality.submissions for select using (auth.uid() = user_id);
-- Admins can view all submissions (policy check)
create policy "Admins can view all submissions." on personality.submissions for select using (
  exists (
    select 1 from personality.profiles
    where profiles.id = auth.uid() and profiles.role = 'ADMIN'
  )
);


-- 4. Seed the database with sample Enneagram test questions
-- (A shortened sample for development. A real test would have 90-135 questions)
insert into personality.questions (text, type_associated) values
  ('I strive for perfection and feel frustrated when things are not done to a high standard.', 1),
  ('It is very important to me to maintain strict ethical standards and do the ''right'' thing.', 1),
  ('Do not consider being a perfectionist a negative thing and like to make sure all the details are just right.', 1),
  ('Have a strong sense of right and wrong and strive for perfection.', 1),
  ('Morals and ethics are more important than compassion and tolerance.', 1),
  ('Easily discern what is wrong in a situation and how it could be done better.', 1),
  ('Believe that rules, regulations, policies, and procedures have a purpose and should be followed and I''m frustrated when others break rules.', 1),
  ('Take pride in being self-disciplined, moderate, and fair.', 1),
  ('Personal integrity is extremely important to me.', 1),
  ('Tend to see the glass as ''half empty'' and to look for what needs fixing.', 1),
  ('Critical of myself (my own worst critic) and find it easy to be judgmental and critical of other people as well.', 1),
  ('Motivated by the need to be correct, fair, and self-disciplined.', 1),
  ('Value being well organized and punctual in myself and others.', 1),
  ('Can be critical, cynical, and argumentative and can act intellectually superior.', 1),
  ('I naturally evaluate things and notice how they could be improved.', 1),
  ('I hold myself to a very high standard and expect others to do the same.', 1),
  ('I often feel a strong sense of internal obligation or duty.', 1),
  ('I am hard on myself when I make a mistake.', 1),
  ('I feel responsible for making sure things are done correctly.', 1),
  ('I actively try to suppress my anger, but it sometimes leaks out as resentment.', 1),

  ('I often put the needs of others before my own and love feeling needed.', 2),
  ('I frequently go out of my way to support, flatter, and care for the people in my life.', 2),
  ('Believe it is important to understand my own and other people’s feelings.', 2),
  ('Have trouble saying no to requests.', 2),
  ('Listen patiently and can be very understanding and comforting to friends.', 2),
  ('I''m told I’m a ''nice person'' and dislike putting myself first.', 2),
  ('Have a strong need to be noticed, liked, and appreciated for what I do for others.', 2),
  ('Like feeling indispensable and helping others become successful.', 2),
  ('Motivated by the need to be appreciated, loved, and connected to people.', 2),
  ('Work very hard at maintaining relationships.', 2),
  ('Know how to get people to like me.', 2),
  ('Have lots of friends and acquaintances and support them by cheering them up.', 2),
  ('See myself as caring and helpful and like to make people feel special and loved.', 2),
  ('Giving feels more comfortable than receiving.', 2),
  ('Believe that my motives for helping others are noble and helpful.', 2),
  ('Tend to be caring, warm, and loyal when not stressed.', 2),
  ('Avoid expressing negative feelings and like to compliment and flatter people.', 2),
  ('Can act like a martyr when not appreciated.', 2),
  ('Consider relationships the most important part of my life.', 2),
  ('I find it difficult to ask for help because I prefer to be the one helping.', 2),

  ('I am highly driven by success and want to be recognized for my achievements.', 3),
  ('I am very adaptable and can easily change my persona to suit different social or professional situations.', 3),
  ('Want to be ''number one'' and I''m confident in my abilities.', 3),
  ('Work hard and know how to get things done.', 3),
  ('Good at marketing and selling myself and my ideas.', 3),
  ('Value exceeding standards and rising to the top of my profession.', 3),
  ('Find it easy to adapt to different people and situations.', 3),
  ('Getting a product to market before the competition is more important than holding it back until it is ''perfect.''', 3),
  ('Tend to be a workaholic and a perfectionist.', 3),
  ('Value finding the most practical, effective way to do a job.', 3),
  ('To impress, I may take on too much and make promises I can’t keep.', 3),
  ('Believe that competition is a good thing and tend to be very competitive.', 3),
  ('Value looking good, presenting a good first impression, and ''dressing for success.''', 3),
  ('Have been goal-oriented for as long as I can remember.', 3),
  ('Believe that negative feelings are an obstacle to getting the job done.', 3),
  ('Motivated by being outstanding and being recognized for my personal success and achievements.', 3),
  ('Enjoy supporting the careers of people whom I care about and who deserve it.', 3),
  ('Love to work and be productive, and work has tended to be a top priority in my life.', 3),
  ('I measure my value by what I am able to accomplish.', 3),
  ('I am very conscious of my public image and how others perceive my success.', 3),

  ('I often feel fundamentally different from others and long for deep, authentic understanding.', 4),
  ('I experience deep, complex emotions and tend to focus heavily on what is missing in my life.', 4),
  ('Creative and have an artistic view of life.', 4),
  ('I feel different from others, as if ''on the outside looking in.''', 4),
  ('Tend to be overly sensitive.', 4),
  ('Can be caught in a fantasy world of romance and imagination.', 4),
  ('Feel envious of other people’s relationships, lifestyles, and accomplishments.', 4),
  ('Can be deeply hurt by the slightest criticism.', 4),
  ('Tend to experience more melancholy than most people I know.', 4),
  ('Enjoy having elegant, refined, unique things that no one else has.', 4),
  ('People have seen me as overly dramatic.', 4),
  ('Tend to be romantic and long for the great love of my life to come along.', 4),
  ('Tend to be reflective and to search for the meaning of my life.', 4),
  ('Feel that something is missing in my life.', 4),
  ('Thrive in environments where I can express my creativity.', 4),
  ('Tend to be more emotional than most people I know.', 4),
  ('Strive to be unique and have done things to avoid being ordinary.', 4),
  ('Tend to be moody, withdrawn, and self-absorbed when stressed.', 4),
  ('When misunderstood, can become withdrawn, self-conscious, and/or rebellious.', 4),
  ('Manners and good taste are extremely important to me.', 4),

  ('I need a significant amount of private time to recharge and process my thoughts independently.', 5),
  ('I prefer to observe situations from a safe distance and gather information rather than jump right in.', 5),
  ('Tend to be shy and withdrawn, especially at social events.', 5),
  ('Enjoy spending time alone pursuing my personal interests.', 5),
  ('Tend to be more logical than emotional.', 5),
  ('Enjoy having control of my own time and private space.', 5),
  ('Rely on facts rather than emotions to make decisions.', 5),
  ('Prefer people not to know how I feel or what I think unless I tell them.', 5),
  ('Have been told I am not in touch with my emotions.', 5),
  ('Don’t mind working alone and enjoy being self-sufficient.', 5),
  ('Enjoy the sense of independence that comes from living frugally.', 5),
  ('Enjoy analyzing things, gathering data, and figuring out what makes things tick.', 5),
  ('Tend to be more comfortable expressing ideas than emotions, especially spontaneously.', 5),
  ('May hesitate while I try to organize my thoughts and may not speak at all if I’m not comfortable with what I want to say.', 5),
  ('Tend to socialize with people who are interested in the same things I am.', 5),
  ('Have ideas, theories, and opinions about almost everything.', 5),
  ('Tend to be distant, stubborn, and pessimistic when stressed.', 5),
  ('Tend to be insightful, objective, and sensitive when not stressed.', 5),
  ('Get tired easily and would love to take time during the day to relax and renew my energy.', 5),
  ('I feel my energy is easily depleted by too much social interaction.', 5),

  ('I naturally tend to anticipate worst-case scenarios and prepare for what could go wrong.', 6),
  ('Loyalty, guidance, and security are the most important things to me in my relationships.', 6),
  ('Safety and security are priorities in my life.', 6),
  ('Tend to worry more than other people.', 6),
  ('Fear being criticized or judged as being improper by other people.', 6),
  ('Have difficulty seeing the ''gray'' areas of an issue and tend to see things in black and white.', 6),
  ('Look for danger, unsafe people, or unsafe situations.', 6),
  ('Try to prepare for every contingency.', 6),
  ('In a relationship, it has been difficult for me to trust the commitment of the other person.', 6),
  ('Doubt my own decisions and opinions about myself.', 6),
  ('Making decisions on my own may cause me anxiety.', 6),
  ('Suspicious of others and wonder about their motives.', 6),
  ('Motivated by the need to acquire security and social support.', 6),
  ('Value the belief that everything is going to be all right yet often lack faith in this belief.', 6),
  ('Believe it is important for people to be with other people or to belong to a group or an organization.', 6),
  ('Friends and family provide the support I feel is necessary in life.', 6),
  ('Tend to be suspicious, anxious, and defensive when stressed.', 6),
  ('When feeling anxious I can be overly vigilant and controlling.', 6),
  ('Don’t really trust anybody I haven’t known for a long time.', 6),
  ('I often look to authority figures or a belief system for guidance.', 6),

  ('I hate feeling trapped or bored, so I am always brainstorming my next exciting adventure.', 7),
  ('I actively try to keep things positive and often distract myself to avoid dealing with painful emotions.', 7),
  ('Have difficulty making decisions because ''everything looks good.''', 7),
  ('Tend to be excited and impatient about accomplishing plans.', 7),
  ('Tend to go overboard in the pursuit of fun and pleasure.', 7),
  ('Need to feel stimulated and like new, fun, exciting, and different things.', 7),
  ('People may find it difficult to follow my train of thought.', 7),
  ('Motivated to feel excited, satisfied, and happy and to do and experience more.', 7),
  ('Like to be ''on the go'' and may appear hyperactive to people.', 7),
  ('Become frustrated if there is not enough time to do all the fun things I want to do.', 7),
  ('Like doing more than one or two things at a time; enjoy ''multitasking.''', 7),
  ('Tend to be fun-loving, imaginative, and optimistic when not stressed.', 7),
  ('Like to entertain and enjoy telling stories and getting laughs.', 7),
  ('Feel that life is to be enjoyed and I''m optimistic about the future.', 7),
  ('Hate to be bored and avoid doing boring, mundane things.', 7),
  ('See no value in enduring suffering and pain and try to avoid it.', 7),
  ('Like to leave my options open; ''don’t hem me in'' describes me well.', 7),
  ('Enjoy trying many things and can do many different things fairly well.', 7),
  ('Talkative, playful, and at times uninhibited.', 7),
  ('Tend to do things in excess and to always want more.', 7),

  ('I am not afraid of confrontation and will fiercely stand up for myself and protect those I care about.', 8),
  ('I like to be completely in control of my environment and strongly dislike showing vulnerability or weakness.', 8),
  ('Like taking risks and the excitement of competition.', 8),
  ('Love to be challenged and enjoy a good fight.', 8),
  ('Find it difficult to forgive and can carry a grudge for a long time.', 8),
  ('Tend to be rebellious, controlling, and insensitive when stressed.', 8),
  ('Stand up for what I want and need in life.', 8),
  ('When afraid of something, I’ve done what was necessary to overcome my fear.', 8),
  ('Easily annoyed by people who act unintelligent or uninformed.', 8),
  ('Value strength and autonomy, take pride in taking care of my own needs, and expect others to do the same for themselves.', 8),
  ('Have difficulty admitting I’m wrong.', 8),
  ('Impatient with people who are indirect or indecisive.', 8),
  ('Dislike people nagging me; this makes me quite stubborn.', 8),
  ('Like expressing my power and being the boss and/or being in charge.', 8),
  ('Feel I must take charge because I''m the strongest and most decisive person in the group.', 8),
  ('Proud about being direct, telling it ''like it is,'' and expressing ''tough love.''', 8),
  ('I''m uncomfortable expressing emotions other than anger.', 8),
  ('I''m assertive and like to compete and win.', 8),
  ('I''m not gullible; you must earn my trust, and I will challenge your loyalty.', 8),
  ('Motivated by the need to protect myself and my loved ones and to be powerful and in control of my life.', 8),

  ('I usually go along with what others want to avoid conflict and keep the peace.', 9),
  ('I can easily see all sides of an argument, which sometimes makes it hard for me to form my own strong opinions.', 9),
  ('Tend to procrastinate and ignore problems or brush them under the rug.', 9),
  ('Dislike being around pessimistic, negative people.', 9),
  ('When feeling relaxed I tend to be friendly and responsive to people.', 9),
  ('Tend to be withdrawn, forgetful, stubborn, and passive-aggressive when stressed.', 9),
  ('Dislike confrontation and try to keep the peace.', 9),
  ('Can be forgetful, neglectful, and ''fuzzy'' about details.', 9),
  ('Easygoing, ''laid back,'' and optimistic.', 9),
  ('Attracted to habits and routines, can relax easily and tune out reality through TV, daydreaming, a good book, etc.', 9),
  ('Can feel angry even though I might look peaceful.', 9),
  ('Can be a ''homebody'' and enjoy the comfort and peace of home.', 9),
  ('Tend to go along with what people say just to get them off my back.', 9),
  ('Too much to do or too many decisions to make can make me angry, anxious, and/or depressed.', 9),
  ('In relationships, I seek harmony and peace through a sense of belonging and/or by bonding with the other person.', 9),
  ('Try to avoid confrontations.', 9),
  ('May do routine and unimportant things before I tackle an important job.', 9),
  ('Motivated by the need to maintain peace of mind and harmony in my life.', 9),
  ('Have difficulty understanding why people settle for second best.', 9),
  ('I find comfort in familiar routines and dislike sudden disruptions.', 9);
